kind: pipeline

steps:
- name: step1a
  image: ubuntu
  commands: 
    - sleep 3
- name: step1b
  image: ubuntu
  commands: 
    - sleep 3
  
- name: step2a
  image: ubuntu
  commands: 
    - sleep 3
  depends_on: [ step1a, step1b ]
- name: step2b
  image: ubuntu
  commands: 
    - sleep 3
  depends_on: [ step1a, step1b ]

- name: step3
  image: ubuntu
  commands: 
    - sleep 3
  depends_on: [ step2a, step2b ]
